#!/bin/bash

usage()
{
    echo "Wrapper script to run CBD iteratively"
    echo "The idea is to run it n times, and for k > 0, reuse generated seeds from the k - 1 run"
    echo "Usage : cbd-iterative <number_of_iterations> <cbd_options...>"
    echo "  To see <cbd_options...>, run cbd without args"
}

log()
{
    echo -e "\033[1;33m[CBD-iterative]\033[0m $1"
}

copy_seeds()
{
    CBD_OUTPUT="$1"

    rm -rf seeds
    mkdir seeds

    # Directories generation
    for DIR in `ls $CBD_OUTPUT/afl`
    do
        mkdir seeds/$DIR
    done

    # Seeds copy
    for DIR in `find $CBD_OUTPUT/afl -type d | grep -o "^.*queue$" | sort | uniq`
    do
        DISCRIMINANT=`echo "$DIR" | grep -o "afl/[0-9]*/coreid=[0-9]*"`
        CBD_STAGE=`echo "$DISCRIMINANT" | cut -d'/' -f2`
        COREID=`echo "$DISCRIMINANT" | cut -d'/' -f3`

        cp -r "$DIR" seeds/$CBD_STAGE/$COREID/
    done
}

link_wildcards()
{
    CBD_OUTPUT="$1"

    rm -rf wildcards
    mkdir wildcards

    # Directories generation
    for DIR in `ls $CBD_OUTPUT/wildcards`
    do
        mkdir wildcards/$DIR

        for DIR2 in `ls $CBD_OUTPUT/wildcards/$DIR`
        do
            mkdir wildcards/$DIR/$DIR2
        done
    done

    find ./seeds -type f > seeds.list

    # Wildcards linking
    for FIC in `find $CBD_OUTPUT/wildcards -type f`
    do
        DISCRIMINANT=`echo "$FIC" | grep -o "wildcards/[0-9]*/coreid=[0-9]*"`
        CBD_STAGE=`echo "$DISCRIMINANT" | cut -d'/' -f2`
        COREID=`echo "$DISCRIMINANT" | cut -d'/' -f3`
        WILDCARD_FILENAME=`basename $FIC`

        grep "$WILDCARD_FILENAME" seeds.list > /dev/null 2>&1

        # If the current wildcard is useful, we link it, otherwise no...
        if [ $? -eq 0 ]
        then
            ln "$FIC" wildcards/$CBD_STAGE/$COREID/
        fi
    done

    rm -f seeds.list
}

get_fuzzing_time_for_the_current_iteration()
{
    FUZZING_TIMES_PER_ITERATION_NUMBER_INTERVAL="$1" # Example : "0-9:3,10-19:10"
    CURRENT_ITERATION_NUMBER="$2"

    STOP=0
    I=1

    while [ $STOP -eq 0 ]
    do
        CURRENT_TIME_SPEC=`echo $FUZZING_TIMES_PER_ITERATION_NUMBER_INTERVAL | cut -d',' -f$I` # 0-9:3
        CURRENT_TIME_SPEC_ASSOCIATED_TIME=`echo $CURRENT_TIME_SPEC | cut -d':' -f2` # 3
        CURRENT_TIME_SPEC_ITERATIONS_INTERVAL=`echo $CURRENT_TIME_SPEC | cut -d':' -f1` # 0-9
        CURRENT_ITERATION_TIME_BOTTOM_ITERATION_NUMBER=`echo $CURRENT_TIME_SPEC_ITERATIONS_INTERVAL | cut -d'-' -f1` # 0
        CURRENT_ITERATION_TIME_TOP_ITERATION_NUMBER=`echo $CURRENT_TIME_SPEC_ITERATIONS_INTERVAL | cut -d'-' -f2` # 9

        if [ "x$CURRENT_TIME_SPEC" == "x" ]
        then
            STOP=1
            RESULT=-1
        elif [ $CURRENT_ITERATION_TIME_BOTTOM_ITERATION_NUMBER -le $CURRENT_ITERATION_NUMBER ] && [ $CURRENT_ITERATION_TIME_TOP_ITERATION_NUMBER -ge $CURRENT_ITERATION_NUMBER ]
        then
            STOP=1
            RESULT=$CURRENT_TIME_SPEC_ASSOCIATED_TIME
        else
            I=$((I + 1))
        fi
    done

    echo "$RESULT"
}

build_args_to_use_seeds()
{
    CBD_ARGS="$1"
    ITERATION_NUMBER="$2"

    read -a CBD_ARGS_ARRAY <<< "$CBD_ARGS"

    if [ "x$CBD_ITERATIVE_TIME_PER_ITERATIONS_ITERVAL" != "x" ]
    then
        TIME_FOR_THIS_ITERATION=`get_fuzzing_time_for_the_current_iteration "$CBD_ITERATIVE_TIME_PER_ITERATIONS_ITERVAL" $ITERATION_NUMBER`
    else
        TIME_FOR_THIS_ITERATION=-1
    fi

    if [[ "x${CBD_ARGS_ARRAY[0]}" =~ "x-" ]]
    then
        CBD_ARGS_ARRAY[0]="${CBD_ARGS_ARRAY[0]}ie"
    fi

    NEW_CBD_ARGS_ARRAY=()

    for I in `seq 0 5`
    do
        NEW_CBD_ARGS_ARRAY[$I]=${CBD_ARGS_ARRAY[$I]}
    done

    NEW_CBD_ARGS_ARRAY[6]="./seeds"
    NEW_CBD_ARGS_ARRAY[7]="./wildcards"
    NEW_CBD_ARGS_ARRAY[8]="$ITERATION_NUMBER"

    for I in `seq 6 $((${#CBD_ARGS_ARRAY[@]} - 1))`
    do
        NEW_CBD_ARGS_ARRAY[$((I + 3))]=${CBD_ARGS_ARRAY[$I]}
    done

    if [ $TIME_FOR_THIS_ITERATION -gt -1 ]
    then
        if echo ${NEW_CBD_ARGS_ARRAY[0]} | grep -- "T" > /dev/null 2>&1
        then
            ADVERSARIAL_SEQUENCES_DEPTH=${NEW_CBD_ARGS_ARRAY[4]}
            TIME_FOR_THIS_ITERATION_DIVIDED_BY_ADVERSARIAL_SEQUENCES_DEPTH=`python3 -c "print($TIME_FOR_THIS_ITERATION / $ADVERSARIAL_SEQUENCES_DEPTH)"`

            for I in `seq 1 $ADVERSARIAL_SEQUENCES_DEPTH`
            do
                if [ $I -eq 1 ]
                then
                    NEW_CBD_FUZZING_TIME=$TIME_FOR_THIS_ITERATION_DIVIDED_BY_ADVERSARIAL_SEQUENCES_DEPTH
                else
                    NEW_CBD_FUZZING_TIME="$NEW_CBD_FUZZING_TIME,$TIME_FOR_THIS_ITERATION_DIVIDED_BY_ADVERSARIAL_SEQUENCES_DEPTH"
                fi
            done

            NEW_CBD_ARGS_ARRAY[3]="$NEW_CBD_FUZZING_TIME"
        else
            NEW_CBD_ARGS_ARRAY[3]=$TIME_FOR_THIS_ITERATION
        fi
    fi

    echo ${NEW_CBD_ARGS_ARRAY[@]}
}

cbd_iterative_function()
{
    NB_ITERATIONS=$1
    CBD_ARGS=$2

    if [ "$NB_ITERATIONS" -gt 0 ]
    then
        log "First iteration"

        CBD_OPTIONS=`echo $CBD_ARGS | cut -d' ' -f1`
        CBD_OTHER_ARGS=`echo $CBD_ARGS | cut -d ' ' -f2-`

        echo $CBD_OPTIONS | grep r > /dev/null 2>&1

        if [ $? -eq 0 ] # If -r is set
        then
            CBD_OPTIONS=`echo $CBD_OPTIONS | sed -re "s/r//g"`

            CBD_ARGS_ITERATION_0="$CBD_OPTIONS $CBD_OTHER_ARGS"
        else
            CBD_ARGS_ITERATION_0=$CBD_ARGS
        fi

        cbd $CBD_ARGS_ITERATION_0

        mv output cbd_output_iteration_0

        log "First iteration : Linking seeds and wildcards"

        copy_seeds cbd_output_iteration_0
        link_wildcards cbd_output_iteration_0

        I=1

        for I in `seq $I $((NB_ITERATIONS - 1))`
        do
            log "Iteration $I"

            CBD_ARGS_FOR_THIS_ITERATION="`build_args_to_use_seeds "$CBD_ARGS" "$I"`"

            export CBD_ALREADY_TREATED_CONCRETE_INPUTS_SHA256_SUMS_PATH=cbd_output_iteration_$((I - 1))/__sha256_sums__

            cbd $CBD_ARGS_FOR_THIS_ITERATION

            log "Iteration $I : Linking seeds and wildcards"

            mv output cbd_output_iteration_$I
            copy_seeds cbd_output_iteration_$I
            link_wildcards cbd_output_iteration_$I
        done
    else
        echo "ERROR : The Number of iteration < 0 (Value : $NB_ITERATIONS)"
    fi
}

if [ $# -lt 2 ]
then
    usage
else
    NB_ITERATIONS=$1

    shift

    CBD_ARGS="$@"

    cbd_iterative_function $NB_ITERATIONS "$CBD_ARGS"
fi