#ifndef CSLPROCESS_RUN_HPP
#define CSLPROCESS_RUN_HPP

#include <optional>
#include <string>
#include <vector>

namespace external_tools_runs
{

class CSLProcessRun;

} // namespace external_tools_runs

#include "helpers/runnables/external_binary_execution.hpp"

namespace external_tools_runs
{

/**
 * @brief Runs a CSLProcess instance
 * 
 */
class CSLProcessRun
{
    private:
        std::string cslFilePath;
        int maxSequencesDepth;
        std::vector<std::string> binaryToTestArgs;
        std::string outputDir;
        std::optional<helpers::runnables::ExternalBinaryExecution> cslProcessExecution;

    public:
        /**
         * @brief Construct a new CSLProcessRun object.
         * 
         * @param _cslFilePath Path to the CSL specification file.
         * @param _maxSequencesDepth Maximal depth of adversarial sequences.
         * @param _binaryToTestArgs Args to pass to the target to test it against generated adversarial sequences in form of a vector of `std::string`.
         * @param _outputDir Output directory for the stuff generated by CSLProcess.
         */
        CSLProcessRun(std::string _cslFilePath, int _maxSequencesDepth, std::vector<std::string> _binaryToTestArgs, std::string _outputDir);

        /**
         * @brief Run and wait CSL Process.
         * 
         */
        void runAndWaitCSLProcess();
};

} // namespace external_tools_runs

#endif